In [1]:
import numpy as np

In [4]:
arr1=np.array([1.,2.,3.,4.,5.,6.]) #shape
arr1.shape

(6,)

In [6]:
arr2=np.array([[1,2,3],[4,5,6],[2,6,8]])
arr2.shape

(3, 3)

In [7]:
arr3=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [8]:
arr3.shape

(2, 2, 2)

In [9]:
arr3.ndim #it shows demension of array

3

In [10]:
arr2.ndim

2

In [11]:
arr3.size  #size

8

In [12]:
arr2.size

9

In [14]:
arr3.itemsize #itemsize

8

In [15]:
arr2.itemsize

8

In [19]:
arr1.itemsize

8

In [21]:
arr2.dtype    #dtype

dtype('int64')

In [22]:
arr1.dtype

dtype('int64')

In [23]:
arr2.astype('float')     #astype

array([[1., 2., 3.],
       [4., 5., 6.],
       [2., 6., 8.]])

In [24]:
arr1.astype('float')

array([1., 2., 3., 4., 5., 6.])