In [7]:
#broadcasting
import numpy as np

In [9]:
#senario 1
arr1=np.arange(8).reshape(2,4)
arr2=np.arange(8,16).reshape(2,4)

In [11]:
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
arr2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
arr1+arr2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [14]:
#senario 2
#if y=1 and x=n then also operation will take place
a=np.arange(9).reshape(3,3)
b=np.arange(3).reshape(1,3)

In [15]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
print(a,b)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [17]:
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [20]:
#if y=1 and x!=n then also operation will not take place
a1=np.arange(9).reshape(3,3)
b1=np.arange(4).reshape(1,4)

In [25]:
print(a1,b1)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]
