In [1]:
#functions of numpy library
import numpy as np

In [4]:
np.random.random()

0.14473019186670877

In [9]:
np.random.seed(1) #give same random value again and again
np.random.random()

0.417022004702574

In [11]:
np.random.uniform(3,10) #give random value btw range(3,10)

3.000800623721414

In [13]:
np.random.uniform(1,100,10) #give 10 random value btw 1,100

array([87.9336262 ,  3.71137173, 67.37628351, 42.31317543, 56.31029302,
       14.89830692, 20.61204742, 80.2737123 , 96.857896  , 32.02899364])

In [14]:
np.random.uniform(1,100,10).reshape(2,5)

array([[69.53993895, 87.76252608, 89.56605969,  9.41937693,  4.86642354],
       [17.81321154, 87.93610784, 10.73633655, 42.68965488, 95.83106348]])

In [15]:
np.random.randint(1,9) #give random integer value btw range

2

In [16]:
np.random.randint(1,10,5)

array([4, 5, 9, 2, 5], dtype=int32)

In [17]:
np.random.randint(1,20,10).reshape(5,2)

array([[17, 14],
       [10, 19],
       [16,  1],
       [ 5, 16],
       [ 3,  8]], dtype=int32)

In [19]:
a=np.random.randint(1,10,6)

In [23]:
a

array([9, 7, 4, 8, 8, 5], dtype=int32)

In [24]:
np.max(a)

np.int32(9)

In [25]:
np.min(a)

np.int32(4)

In [26]:
np.argmax(a) #index of max value

np.int64(0)

In [27]:
np.argmin(a) #index of min value

np.int64(2)

In [28]:
a

array([9, 7, 4, 8, 8, 5], dtype=int32)

In [30]:
#replace odd value with -1
a[a%2!=0]=-1
a

array([-1, -1,  4,  8,  8, -1], dtype=int32)

In [31]:
#where(condition,true,false)

array([-1, -1,  4,  8,  8, -1], dtype=int32)

In [33]:
a=np.random.randint(1,50,6)
a

array([35, 11, 24, 16, 48, 24], dtype=int32)

In [34]:
np.where(a%2==1,-1,a)

array([-1, -1, 24, 16, 48, 24], dtype=int32)

In [35]:
a=np.random.randint(1,60,10)
a

array([26,  8, 52, 29, 11, 47, 33, 25, 24, 56], dtype=int32)

In [36]:
np.sort(a)

array([ 8, 11, 24, 25, 26, 29, 33, 47, 52, 56], dtype=int32)

In [37]:
#percentile

In [38]:
np.percentile(a,25)

np.float64(24.25)