In [2]:
#creating numpy n-d array
import numpy as np

In [6]:
arr1=np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr2=np.zeros((2,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr3=np.ones((2,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr5=np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr6=np.identity(5)
arr6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        ])

In [18]:
arr8=arr7.copy()
arr8

array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        ])